# applies location and environment labels to cluster
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: anthos-sample-cluster1
  labels:
    environment: prod
    location: newyork