apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: proxy
  annotations:
    configmanagement.gke.io/managed: enabled
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      cluster: newyork
  template:
    metadata:
      labels:
        app: nginx
        cluster: newyork
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx

